In [75]:
pip install numpy

Requirement already satisfied: numpy in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

In [76]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [77]:
import numpy as np
import pandas as pd

In [78]:
data=pd.read_csv('Row_data.csv')
data.head()

,transaction_id,customer_id,transaction_date,customer_age,customer_location,quantity,unit_price,total_amount,payment_method,shipping_speed,customer_history_orders,discount_applied,discount_percentage,shipping_cost,delivery_time_days,refund_requested,velocity_flag,geolocation_mismatch,device_fingerprint_new,involves_counterfeit
0,TXN_957334,CUST_11907,2024-10-12 03:52:13,22,JP,1,199.66,199.66,Debit Card,Express,17,False,0.0,5.39,26,False,False,False,False,False
1,TXN_246397,CUST_27641,2024-08-18 00:36:57,62,DE,4,116.01,464.03,PayPal,Express,36,False,0.0,8.18,25,False,False,False,False,False
2,TXN_403072,CUST_78628,2024-08-19 22:21:30,75,DE,1,42.04,42.04,Credit Card,Priority,21,False,0.0,8.61,27,False,False,False,False,False
3,TXN_848560,CUST_98579,2025-04-16 18:49:39,56,BR,3,147.69,443.08,Credit Card,Standard,14,True,48.7,17.00,26,False,False,False,False,False
4,TXN_270817,CUST_67519,2024-10-06 13:30:52,19,IN,4,40.70,162.80,PayPal,Priority,48,False,0.0,20.53,1,False,False,True,False,False

In [79]:
data.info

<bound method DataFrame.info of      transaction_id customer_id     transaction_date  customer_age  \
0        TXN_957334  CUST_11907  2024-10-12 03:52:13            22
1        TXN_246397  CUST_27641  2024-08-18 00:36:57            62
2        TXN_403072  CUST_78628  2024-08-19 22:21:30            75
3        TXN_848560  CUST_98579  2025-04-16 18:49:39            56
4        TXN_270817  CUST_67519  2024-10-06 13:30:52            19
...             ...         ...                  ...           ...
2995     TXN_871091  CUST_24811  2025-05-15 21:20:07            54
2996     TXN_962121  CUST_83828  2024-09-09 16:59:59            33
2997     TXN_816757  CUST_66695  2025-02-26 20:40:23            19
2998     TXN_116346  CUST_87035  2024-12-21 03:07:24            19
2999     TXN_110910  CUST_47783  2025-03-10 21:24:48            35

     customer_location  quantity  unit_price  total_amount payment_method  \
0                   JP         1      199.66        199.66     Debit Card
1                   DE         4      116.01        464.03         PayPal
2                   DE         1       42.04         42.04    Credit Card
3                   BR         3      147.69        443.08    Credit Card
4                   IN         4       40.70        162.80         PayPal
...                ...       ...         ...           ...            ...
2995                JP         3       61.99        185.98     Debit Card
2996                JP         3      102.99        308.96      Apple Pay
2997                JP         4      156.37        625.47      Apple Pay
2998                AU         1      227.47        227.47      Apple Pay
2999                CA         2       27.45         54.90         PayPal

     shipping_speed  customer_history_orders  discount_applied  \
0           Express                       17             False
1           Express                       36             False
2          Priority                       21             False
3          Standard                       14              True
4          Priority                       48             False
...             ...                      ...               ...
2995        Express                       24              True
2996        Express                       44             False
2997       Priority                       20             False
2998        Express                        1             False
2999       Priority                       17             False

      discount_percentage  shipping_cost  delivery_time_days  \
0                     0.0           5.39                  26
1                     0.0           8.18                  25
2                     0.0           8.61                  27
3                    48.7          17.00                  26
4                     0.0          20.53                   1
...                   ...            ...                 ...
2995                 39.0          12.28                  22
2996                  0.0          14.92                  10
2997                  0.0           5.49                  24
2998                  0.0          22.22                  28
2999                  0.0          17.03                  19

      refund_requested  velocity_flag  geolocation_mismatch  \
0                False          False                 False
1                False          False                 False
2                False          False                 False
3                False          False                 False
4                False          False                  True
...                ...            ...                   ...
2995             False          False                 False
2996             False          False                 False
2997             False          False                 False
2998             False          False                 False
2999             False          False                 False

      device_fingerprint_new  involves_counterfeit
0                      False                 False
1                      False                 False
2                      False                 False
3                      False                 False
4                      False                 False
...                      ...                   ...
2995                   False                 False
2996                    True                 False
2997                   False                 False
2998                   False                 False
2999                   False                 False

[3000 rows x 20 columns]>

In [80]:
data.shape

(3000, 20)

In [81]:
data.isnull().sum()

transaction_id             0
customer_id                0
transaction_date           0
customer_age               0
customer_location          0
quantity                   0
unit_price                 0
total_amount               0
payment_method             0
shipping_speed             0
customer_history_orders    0
discount_applied           0
discount_percentage        0
shipping_cost              0
delivery_time_days         0
refund_requested           0
velocity_flag              0
geolocation_mismatch       0
device_fingerprint_new     0
involves_counterfeit       0
dtype: int64

In [82]:
data.duplicated().sum()

np.int64(0)

In [83]:
data.describe

<bound method NDFrame.describe of      transaction_id customer_id     transaction_date  customer_age  \
0        TXN_957334  CUST_11907  2024-10-12 03:52:13            22
1        TXN_246397  CUST_27641  2024-08-18 00:36:57            62
2        TXN_403072  CUST_78628  2024-08-19 22:21:30            75
3        TXN_848560  CUST_98579  2025-04-16 18:49:39            56
4        TXN_270817  CUST_67519  2024-10-06 13:30:52            19
...             ...         ...                  ...           ...
2995     TXN_871091  CUST_24811  2025-05-15 21:20:07            54
2996     TXN_962121  CUST_83828  2024-09-09 16:59:59            33
2997     TXN_816757  CUST_66695  2025-02-26 20:40:23            19
2998     TXN_116346  CUST_87035  2024-12-21 03:07:24            19
2999     TXN_110910  CUST_47783  2025-03-10 21:24:48            35

     customer_location  quantity  unit_price  total_amount payment_method  \
0                   JP         1      199.66        199.66     Debit Card
1                   DE         4      116.01        464.03         PayPal
2                   DE         1       42.04         42.04    Credit Card
3                   BR         3      147.69        443.08    Credit Card
4                   IN         4       40.70        162.80         PayPal
...                ...       ...         ...           ...            ...
2995                JP         3       61.99        185.98     Debit Card
2996                JP         3      102.99        308.96      Apple Pay
2997                JP         4      156.37        625.47      Apple Pay
2998                AU         1      227.47        227.47      Apple Pay
2999                CA         2       27.45         54.90         PayPal

     shipping_speed  customer_history_orders  discount_applied  \
0           Express                       17             False
1           Express                       36             False
2          Priority                       21             False
3          Standard                       14              True
4          Priority                       48             False
...             ...                      ...               ...
2995        Express                       24              True
2996        Express                       44             False
2997       Priority                       20             False
2998        Express                        1             False
2999       Priority                       17             False

      discount_percentage  shipping_cost  delivery_time_days  \
0                     0.0           5.39                  26
1                     0.0           8.18                  25
2                     0.0           8.61                  27
3                    48.7          17.00                  26
4                     0.0          20.53                   1
...                   ...            ...                 ...
2995                 39.0          12.28                  22
2996                  0.0          14.92                  10
2997                  0.0           5.49                  24
2998                  0.0          22.22                  28
2999                  0.0          17.03                  19

      refund_requested  velocity_flag  geolocation_mismatch  \
0                False          False                 False
1                False          False                 False
2                False          False                 False
3                False          False                 False
4                False          False                  True
...                ...            ...                   ...
2995             False          False                 False
2996             False          False                 False
2997             False          False                 False
2998             False          False                 False
2999             False          False                 False

      device_fingerprint_new  involves_counterfeit
0                      False                 False
1                      False                 False
2                      False                 False
3                      False                 False
4                      False                 False
...                      ...                   ...
2995                   False                 False
2996                    True                 False
2997                   False                 False
2998                   False                 False
2999                   False                 False

[3000 rows x 20 columns]>

In [84]:
data.columns=data.columns.str.lower()

In [85]:
data['transaction_date']=pd.to_datetime(data['transaction_date'])

In [86]:
data.columns

Index(['transaction_id', 'customer_id', 'transaction_date', 'customer_age',
       'customer_location', 'quantity', 'unit_price', 'total_amount',
       'payment_method', 'shipping_speed', 'customer_history_orders',
       'discount_applied', 'discount_percentage', 'shipping_cost',
       'delivery_time_days', 'refund_requested', 'velocity_flag',
       'geolocation_mismatch', 'device_fingerprint_new',
       'involves_counterfeit'],
      dtype='str')

In [87]:
data['age_group']=pd.cut(
    data['customer_age'],
    bins=[17,25,35,45,55,65,100],
    labels=['18-25','26-35','36-45','46-55','56-65','65+']

)
data['age_group'].isnull().sum()

np.int64(0)

In [88]:
data['risk_score'] = (
    data['velocity_flag'].astype(int) +
    data['geolocation_mismatch'].astype(int) +
    data['device_fingerprint_new'].astype(int) +
    data['refund_requested'].astype(int)
)

In [89]:
avg_amount=np.mean(data['total_amount'])
avg_amount

np.float64(431.4155733333334)

In [90]:
median_amonut=np.median(data['total_amount'])
median_amonut

np.float64(322.58500000000004)

In [91]:
std_amount=np.std(data['total_amount'])
std_amount

np.float64(331.0853924440107)

In [92]:
maximun=np.max(data['total_amount'])
display(maximun)
minimum=np.min(data['total_amount'])
display(minimum)

np.float64(1865.66)

np.float64(6.28)

In [93]:
data['involves_counterfeit'].value_counts()

involves_counterfeit
False    2267
True      733
Name: count, dtype: int64

In [94]:
counterfeit_rate=data['involves_counterfeit'].mean()*100
counterfeit_rate

np.float64(24.433333333333334)

In [95]:
payment_analysis=data.groupby('payment_method')['involves_counterfeit'].mean()*100
payment_analysis

payment_method
Apple Pay           0.000000
Credit Card        26.052632
Cryptocurrency    100.000000
Debit Card          0.000000
PayPal             22.049287
Wire Transfer     100.000000
Name: involves_counterfeit, dtype: float64

In [96]:
location_analysis=data.groupby('customer_location')['involves_counterfeit'].mean()*100
location_analysis

customer_location
AU    25.694444
BR    23.684211
CA    23.127036
DE    25.641026
FR    25.373134
GB    24.615385
IN    23.255814
JP    25.249169
MX    22.683706
US    25.266904
Name: involves_counterfeit, dtype: float64

In [97]:
df = pd.read_csv("counterfeit_products.csv")

df.head()

,product_id,seller_id,category,brand,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,...,shipping_origin,views,purchases,wishlist_adds,certification_badges,warranty_months,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit
0,dcb12716,seller_5426,Electronics,DigitalPro,218.54,4.9,5291,7,220,7,...,JP,3454,99,23,2,21,True,False,True,False
1,d1f8b777,seller_4385,Luxury Goods,TechCrop,20.72,3.2,29,2,179,41,...,CA,4127,252,88,0,9,False,False,False,True
2,9989f13a,seller_2528,Fashion,FashionForward,18.87,3.9,14,2,100,25,...,CN,3212,306,6,4,8,True,True,False,True
3,4e008120,seller_8099,Electronics,CircuitMaster,79.27,4.9,8533,4,976,10,...,CN,1488,7,46,2,13,False,False,False,False
4,933b65ba,seller_7873,Luxury Goods,PremiumCraft,225.98,3.8,7655,4,589,6,...,DE,171,9,5,3,13,False,False,False,False

In [98]:
df.columns

Index(['product_id', 'seller_id', 'category', 'brand', 'price',
       'seller_rating', 'seller_reviews', 'product_images',
       'description_length', 'shipping_time_days', 'spelling_errors',
       'domain_age_days', 'contact_info_complete', 'return_policy_clear',
       'payment_methods_count', 'listing_date', 'seller_country',
       'shipping_origin', 'views', 'purchases', 'wishlist_adds',
       'certification_badges', 'warranty_months', 'bulk_orders',
       'unusual_payment_patterns', 'ip_location_mismatch', 'is_counterfeit'],
      dtype='str')

In [99]:
df.isnull().sum()

product_id                  0
seller_id                   0
category                    0
brand                       0
price                       0
seller_rating               0
seller_reviews              0
product_images              0
description_length          0
shipping_time_days          0
spelling_errors             0
domain_age_days             0
contact_info_complete       0
return_policy_clear         0
payment_methods_count       0
listing_date                0
seller_country              0
shipping_origin             0
views                       0
purchases                   0
wishlist_adds               0
certification_badges        0
warranty_months             0
bulk_orders                 0
unusual_payment_patterns    0
ip_location_mismatch        0
is_counterfeit              0
dtype: int64

In [100]:
df.duplicated().sum()

np.int64(0)

In [101]:
df.select_dtypes(include=np.number).columns

Index(['price', 'seller_rating', 'seller_reviews', 'product_images',
       'description_length', 'shipping_time_days', 'spelling_errors',
       'domain_age_days', 'payment_methods_count', 'views', 'purchases',
       'wishlist_adds', 'certification_badges', 'warranty_months'],
      dtype='str')

In [102]:
df['price_category'] = np.where(
    df['price'] < df['price'].median(),
    'Low Price',
    'High Price'
)

In [103]:
df['seller_group'] = np.select(
    [
        df['seller_rating'] >= 4.5,
        df['seller_rating'] >= 3.5
    ],
    [
        'High',
        'Medium'
    ],
    default='Low'
)

In [104]:
df['risk_score'] = (
    df['ip_location_mismatch'].astype(int)
    + df['unusual_payment_patterns'].astype(int)
)

In [105]:
df.isnull().sum().sum()

np.int64(0)

In [106]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [107]:
df.to_excel(
    "counterfeit_products_cleaned.xlsx",
    index=False
)

In [108]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\kk\Desktop\Data Science\venv\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [109]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="CounterfeitDB",
    user="postgres",
    password="divya",
    port="5432"
)

cur = conn.cursor()

print("Connected successfully!")

Connected successfully!

In [110]:
data.to_excel("cleaned_transactions.xlsx", index=False)

In [111]:
data.isnull().sum()

transaction_id             0
customer_id                0
transaction_date           0
customer_age               0
customer_location          0
quantity                   0
unit_price                 0
total_amount               0
payment_method             0
shipping_speed             0
customer_history_orders    0
discount_applied           0
discount_percentage        0
shipping_cost              0
delivery_time_days         0
refund_requested           0
velocity_flag              0
geolocation_mismatch       0
device_fingerprint_new     0
involves_counterfeit       0
age_group                  0
risk_score                 0
dtype: int64

In [112]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:divya@localhost:5432/CounterfeitDB"
)

In [113]:
data.to_sql(
    "counterfeit_transactions",
    engine,
    if_exists="replace",
    index=False
)

print("Table created successfully!")

Table created successfully!

In [114]:
data.to_sql(
    "counterfeit_products",
    engine,
    if_exists="replace",
    index=False
)

print("Table created successfully!")

Table created successfully!

In [116]:
print(df.columns)
print(data.columns)

Index(['product_id', 'seller_id', 'category', 'brand', 'price',
       'seller_rating', 'seller_reviews', 'product_images',
       'description_length', 'shipping_time_days', 'spelling_errors',
       'domain_age_days', 'contact_info_complete', 'return_policy_clear',
       'payment_methods_count', 'listing_date', 'seller_country',
       'shipping_origin', 'views', 'purchases', 'wishlist_adds',
       'certification_badges', 'warranty_months', 'bulk_orders',
       'unusual_payment_patterns', 'ip_location_mismatch', 'is_counterfeit',
       'price_category', 'seller_group', 'risk_score'],
      dtype='str')
Index(['transaction_id', 'customer_id', 'transaction_date', 'customer_age',
       'customer_location', 'quantity', 'unit_price', 'total_amount',
       'payment_method', 'shipping_speed', 'customer_history_orders',
       'discount_applied', 'discount_percentage', 'shipping_cost',
       'delivery_time_days', 'refund_requested', 'velocity_flag',
       'geolocation_mismatch', 'device_fingerprint_new',
       'involves_counterfeit', 'age_group', 'risk_score'],
      dtype='str')